package com.sunny.ai.query.service;

import com.sunny.ai.query.domain.QueryLog;
import com.sunny.ai.query.domain.QueryStatus;
import com.sunny.ai.query.dto.QueryRequest;
import com.sunny.ai.query.dto.QueryResponse;
import com.sunny.ai.query.repository.QueryLogRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.reactive.function.client.WebClient;

import java.time.Instant;
import java.util.List;

/**
 * RAG-based query service: embeds the question, retrieves top-K relevant chunks
 * from the embedding-service, then calls the LLM to generate a grounded answer.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class QueryService {

    private static final String TOPIC_QUERY_EXECUTED = "query-executed";
    private static final String MODEL_USED = "gpt-4o";

    private final QueryLogRepository queryLogRepository;
    private final KafkaTemplate<String, String> kafkaTemplate;
    private final WebClient.Builder webClientBuilder;

    @Value("${services.embedding-service.url:http://embedding-service}")
    private String embeddingServiceUrl;

    @Value("${ai.llm.api-key:mock}")
    private String llmApiKey;

    @Transactional
    public QueryResponse executeQuery(QueryRequest request) {
        long startTime = System.currentTimeMillis();
        log.info("Executing RAG query: {}", request.getQuestion());

        QueryLog queryLog = QueryLog.builder()
                .question(request.getQuestion())
                .userId(request.getUserId())
                .status(QueryStatus.PROCESSING)
                .modelUsed(MODEL_USED)
                .build();
        queryLog = queryLogRepository.save(queryLog);

        try {
            // Step 1: Retrieve top-K relevant chunks from embedding-service
            List<String> retrievedChunkIds = retrieveRelevantChunks(request.getQuestion(), request.getTopK());
            String context = String.join("\n---\n", retrievedChunkIds); // in prod: fetch actual content

            // Step 2: Generate LLM answer using retrieved context
            String answer = generateAnswer(request.getQuestion(), context);

            long responseTime = System.currentTimeMillis() - startTime;

            queryLog.setAnswer(answer);
            queryLog.setRetrievedContext(context);
            queryLog.setStatus(QueryStatus.COMPLETED);
            queryLog.setResponseTimeMs(responseTime);
            queryLogRepository.save(queryLog);

            // Step 3: Publish audit event
            kafkaTemplate.send(TOPIC_QUERY_EXECUTED, queryLog.getId(),
                    "{\"queryId\":\"" + queryLog.getId() + "\",\"userId\":\"" + request.getUserId() + "\"}");

            return QueryResponse.builder()
                    .queryId(queryLog.getId())
                    .question(request.getQuestion())
                    .answer(answer)
                    .sourceChunkIds(retrievedChunkIds)
                    .modelUsed(MODEL_USED)
                    .responseTimeMs(responseTime)
                    .timestamp(Instant.now())
                    .build();

        } catch (Exception e) {
            log.error("Query execution failed: {}", e.getMessage(), e);
            queryLog.setStatus(QueryStatus.FAILED);
            queryLogRepository.save(queryLog);
            throw e;
        }
    }

    private List<String> retrieveRelevantChunks(String question, int topK) {
        // TODO: Call embedding-service via WebClient to get similar chunk IDs
        // WebClient embeddingClient = webClientBuilder.baseUrl(embeddingServiceUrl).build();
        // For now returning mock chunk IDs
        log.debug("Retrieving top {} chunks for question: {}", topK, question);
        return List.of("chunk-001", "chunk-002", "chunk-003");
    }

    private String generateAnswer(String question, String context) {
        if ("mock".equals(llmApiKey)) {
            return "Based on the retrieved context, here is a synthesized answer to: \"" +
                    question + "\". [Mock answer - configure ai.llm.api-key for real LLM responses]";
        }
        // TODO: Call OpenAI / Ollama API with prompt + context
        return "Answer generated by " + MODEL_USED;
    }
}
